name: Deploy MERN (main)

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install sshpass + rsync (for password SSH and safe file sync)
              run: sudo apt-get update && sudo apt-get install -y sshpass rsync

            - name: Deploy to Droplet (password-based SSH)
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }} # e.g., your droplet IP or domain
                  SSH_USERNAME: ${{ secrets.SSH_USERNAME }} # e.g., root or your sudo user
                  SSH_KEY: ${{ secrets.SSH_KEY }} # your SSH PASSWORD (not a key) for sshpass
              run: |
                  set -e
                  sshpass -p "$SSH_KEY" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" << 'EOF'
                  set -e

                  ###############
                  # FRONTEND (Vite in ./frontend)
                  ###############
                  # Choose the repo path you cloned: /var/www/html/site (recommended) or /var/www/html
                  if [ -d /var/www/html/site ]; then
                    REPO_ROOT="/var/www/html/site"
                  else
                    REPO_ROOT="/var/www/html"
                  fi
